# -*- coding: utf-8 -*-
"""Dashboard stunting - afriani

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gPoDGnwhxRLZGy5IeryZD4V4B5AAJ-Xo
"""

!pip install streamlit

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

# --------------------------------------------------
# CONFIG
# --------------------------------------------------
st.set_page_config(page_title="Dashboard Stunting Indonesia", layout="wide")

# --------------------------------------------------
# LOAD DATA
# --------------------------------------------------
DATA_PATH = "/content/OUTPUT CLEAR.xlsx"
df = pd.read_excel(DATA_PATH)

# Pastikan tipe data kolom penting

df["B1R1"] = df["B1R1"].astype(str)       # Provinsi (kode)
df["B4K4"] = df["B4K4"].astype(str)       # Jenis kelamin (kode)
df["B6R1"] = df["B6R1"].astype(str)       # Sumber air (kode)
# Umur bulan sebaiknya integer
try:
    df["B4K7BLN"] = df["B4K7BLN"].astype(int)
except Exception:
    # jika ada NaN atau format lain, tetap biarkan (plotly bisa handle jika tidak numeric)
    pass

# --------------------------------------------------
# MAPPING (Kode -> Label)
# --------------------------------------------------
provinsi_map = {
    "11":"Aceh","12":"Sumatera Utara","13":"Sumatera Barat","14":"Riau","15":"Jambi",
    "16":"Sumatera Selatan","17":"Bengkulu","18":"Lampung","19":"Kep. Bangka Belitung",
    "21":"Kep. Riau","31":"DKI Jakarta","32":"Jawa Barat","33":"Jawa Tengah",
    "34":"DI Yogyakarta","35":"Jawa Timur","36":"Banten","51":"Bali","52":"Nusa Tenggara Barat",
    "53":"Nusa Tenggara Timur","61":"Kalimantan Barat","62":"Kalimantan Tengah",
    "63":"Kalimantan Selatan","64":"Kalimantan Timur","65":"Kalimantan Utara",
    "71":"Sulawesi Utara","72":"Sulawesi Tengah","73":"Sulawesi Selatan",
    "74":"Sulawesi Tenggara","75":"Gorontalo","76":"Sulawesi Barat",
    "81":"Maluku","82":"Maluku Utara",
    "91":"Papua Barat","92":"Papua Barat Daya","94":"Papua",
    "95":"Papua Selatan","96":"Papua Tengah","97":"Papua Pegunungan"
}

jk_map = {"1": "Laki-Laki", "2": "Perempuan"}

air_map = {
    "1": "Air kemasan",
    "2": "Air isi ulang",
    "3": "Ledeng/air perpipaan",
    "4": "Sumur bor/pompa",
    "5": "Sumur gali terlindung",
    "6": "Sumur gali tak terlindung",
    "7": "Mata air terlindung",
    "8": "Mata air tidak terlindung",
    "9": "Penampungan air hujan",
    "10": "Air permukaan (sungai/danau/irigasi)",
    "11": "Hidran air",
    "12": "Terminal air",
    "13": "Air eceran membeli"
}

# Apply mapping to create human-readable columns (keamanan: gunakan .get agar tidak error jika ada kode tak terdefinisi)
df["Provinsi"] = df["B1R1"].map(lambda x: provinsi_map.get(x, "Lainnya"))
df["Jenis_Kelamin"] = df["B4K4"].map(lambda x: jk_map.get(x, "Lainnya"))
df["Sumber_Air"] = df["B6R1"].map(lambda x: air_map.get(x, "Lainnya"))

# --------------------------------------------------
# UI: Tabs
# --------------------------------------------------
tab1, tab2, tab3, tab4, tab5, tab6 = st.tabs([
    "Header",
    "Statistik Deskriptif",
    "Visualisasi dengan Filter",
    "Analisis Perbandingan",
    "Heatmap Korelasi",
    "Tabel Data"
])

# -------------------------
# TAB 1 - Header
# -------------------------
with tab1:
    st.title("📊 Dashboard Stunting Indonesia")
    st.caption("Nama : Afriani Mutia Mardhotillah | NIM : 2403112257")
    st.write(
        "Dashboard ini menampilkan gambaran kondisi kelahiran (Berat dan Panjang Lahir) "
        "beserta faktor pendukung seperti Jenis Kelamin, Umur Anak, Provinsi, dan Sumber Air. "
        "Dashboard terbagi ke dalam beberapa tab agar analisis menjadi lebih terstruktur dan mudah."
    )

# -------------------------
# TAB 2 - Statistik Deskriptif
# -------------------------
with tab2:
    st.header("📊 Statistik Deskriptif Variabel Utama")

    col1, col2, col3 = st.columns(3)

    with col1:
        st.subheader("Berat Badan Lahir (I05A)")
        st.write(df["I05A"].describe())

    with col2:
        st.subheader("Panjang Badan Lahir (I07)")
        st.write(df["I07"].describe())

    with col3:
        st.subheader("Umur Anak (B4K7BLN)")
        # bila kolom numeric
        if pd.api.types.is_numeric_dtype(df["B4K7BLN"]):
            st.write(df["B4K7BLN"].describe())
        else:
            st.write("Kolom B4K7BLN tidak numeric atau kosong.")

    st.subheader("Histogram Variabel Utama")
    c1, c2, c3 = st.columns(3)
    with c1:
        fig_i05a = px.histogram(df, x="I05A", nbins=30, title="Histogram Berat Lahir (I05A)")
        st.plotly_chart(fig_i05a, use_container_width=True)
    with c2:
        fig_i07 = px.histogram(df, x="I07", nbins=30, title="Histogram Panjang Lahir (I07)")
        st.plotly_chart(fig_i07, use_container_width=True)
    with c3:
        # histogram umur (jika numeric)
        if pd.api.types.is_numeric_dtype(df["B4K7BLN"]):
            fig_age = px.histogram(df, x="B4K7BLN", nbins=30, title="Histogram Umur Anak (B4K7BLN)")
            st.plotly_chart(fig_age, use_container_width=True)
        else:
            st.info("Kolom B4K7BLN tidak tersedia atau bukan numeric.")

# -------------------------
# TAB 3 - Visualisasi dengan Filter
# -------------------------
with tab3:
    st.header("📈 Visualisasi Variabel Utama dengan Filter")

    fcol1, fcol2, fcol3, fcol4 = st.columns(4)
    gender_f = fcol1.selectbox("Jenis Kelamin", ["All"] + sorted(df["Jenis_Kelamin"].dropna().unique().tolist()))
    # umur range slider: fallback jika kolom numeric
    if pd.api.types.is_numeric_dtype(df["B4K7BLN"]):
        min_age = int(df["B4K7BLN"].min())
        max_age = int(df["B4K7BLN"].max())
        umur_f = fcol2.slider("Umur Anak (bulan)", min_age, max_age, (min_age, max_age))
    else:
        umur_f = None
        fcol2.write("Umur (B4K7BLN) not numeric")

    prov_f = fcol3.selectbox("Provinsi", ["All"] + sorted(df["Provinsi"].dropna().unique().tolist()))
    air_f = fcol4.selectbox("Sumber Air", ["All"] + sorted(df["Sumber_Air"].dropna().unique().tolist()))

    df_f = df.copy()
    if gender_f != "All":
        df_f = df_f[df_f["Jenis_Kelamin"] == gender_f]
    if prov_f != "All":
        df_f = df_f[df_f["Provinsi"] == prov_f]
    if air_f != "All":
        df_f = df_f[df_f["Sumber_Air"] == air_f]
    if umur_f is not None:
        df_f = df_f[(df_f["B4K7BLN"] >= umur_f[0]) & (df_f["B4K7BLN"] <= umur_f[1])]

    st.subheader("Boxplot Berat & Panjang Lahir (filtered)")
    left, right = st.columns(2)
    with left:
        fig_box_i05a = px.box(df_f, y="I05A", color="Jenis_Kelamin", title="Boxplot Berat Lahir (I05A)")
        st.plotly_chart(fig_box_i05a, use_container_width=True)
    with right:
        fig_box_i07 = px.box(df_f, y="I07", color="Jenis_Kelamin", title="Boxplot Panjang Lahir (I07)")
        st.plotly_chart(fig_box_i07, use_container_width=True)

# -------------------------
# TAB 4 - Analisis Perbandingan
# -------------------------
with tab4:
    st.header("🔍 Analisis Perbandingan Antar Kelompok (Jenis Kelamin)")
    pilihan = st.selectbox("Pilih Variabel untuk Perbandingan", ["I05A", "I07"], index=0)

    if pilihan == "I05A":
        fig_comp = px.histogram(df, x="I05A", color="Jenis_Kelamin", barmode="overlay",
                                labels={"I05A": "Berat Lahir (I05A)"}, title="Perbandingan Berat Lahir berdasarkan Jenis Kelamin")
    else:
        fig_comp = px.histogram(df, x="I07", color="Jenis_Kelamin", barmode="overlay",
                                labels={"I07": "Panjang Lahir (I07)"}, title="Perbandingan Panjang Lahir berdasarkan Jenis Kelamin")

    st.plotly_chart(fig_comp, use_container_width=True)

# -------------------------
# TAB 5 - Heatmap Korelasi
# -------------------------
with tab5:
    st.header("🔥 Heatmap Korelasi Variabel Utama")
    corr_cols = ["I05A", "I07"]
    # sertakan umur jika numeric
    if pd.api.types.is_numeric_dtype(df["B4K7BLN"]):
        corr_cols.append("B4K7BLN")

    corr = df[corr_cols].corr()
    fig_corr = px.imshow(corr, text_auto=True, color_continuous_scale="RdBu_r", zmin=-1, zmax=1,
                        title="Heatmap Korelasi")
    st.plotly_chart(fig_corr, use_container_width=True)

# -------------------------
# TAB 6 - Tabel Data Interaktif
# -------------------------
with tab6:
    st.header("📄 Tabel Data Interaktif")
    show_cols = ["B4K4", "Jenis_Kelamin", "B4K7BLN", "B1R1", "Provinsi", "B6R1", "Sumber_Air", "I05A", "I07"]
    # hanya tampilkan kolom yang ada di df
    show_cols = [c for c in show_cols if c in df.columns]
    st.dataframe(df[show_cols].reset_index(drop=True))